name: Atualizar lista IPTV

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Executar script
      run: python gerar_m3u.py

    - name: Commit e push se houver mudanças
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git pull --rebase
        git add lista.m3u
        git commit -m "Atualização automática da lista IPTV" || echo "Sem mudanças"
        git push
