name: Atualizar lista IPTV

on:
  push:
    paths:
      - canais.json
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar dependências (opcional)
      run: pip install -r requirements.txt || true

    - name: Executar script de geração da lista
      run: python gerar_m3u.py

    - name: Commit e push se houver mudanças
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add lista.m3u
        git diff --cached --quiet || git commit -m "Atualização automática da lista.m3u"
        git push
