name: Atualizar lista IPTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        run: python gerar_m3u.py

      - name: Commit e Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add lista.m3u
          git commit -m 'Atualização automática da lista IPTV'
          git push