name: Atualizar lista IPTV

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Instalar dependências
        run: pip install requests
      - name: Executar script
        run: python gerar_m3u.py
      - name: Commit e Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add lista.m3u
          git commit -m "Atualização automática" || echo "Sem mudanças"
          git push
