name: Converter fontes.txt em canais_temp.json

on:
  push:
    paths:
      - fontes.txt
  workflow_dispatch:

jobs:
  converter:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências (opcional)
        run: pip install beautifulsoup4 requests

      - name: Rodar captura_links.py
        run: python captura_links.py

      - name: Commit e push do canais_temp.json gerado
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add canais_temp.json
          git commit -m "Gerado canais_temp.json a partir do fontes.txt" || echo "Sem mudanças"
          git push
