
name: Gerar lista.m3u a partir de canais.json

on:
  push:
    paths:
      - 'canais.json'
  workflow_dispatch:

jobs:
  gerar_m3u:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip

    - name: Rodar gerar_m3u.py
      run: |
        python gerar_m3u.py

    - name: Commit e push da lista.m3u gerada
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add lista.m3u
        git commit -m 'Atualização automática da lista.m3u' || echo "Sem alterações"
        git push
    