name: Merge canais_temp.json para canais.json

on:
  push:
    paths:
      - 'canais_temp.json'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip

    - name: Rodar merge_canais.py
      run: |
        python merge_canais.py

    - name: Commit e push do canais.json atualizado
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add canais.json
        git commit -m 'Atualização automática do canais.json' || echo "Sem alterações"
        git push
