name: Merge canais_temp.json com canais.json

on:
  push:
    paths:
      - canais_temp.json
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Rodar merge_canais_json.py
        run: python merge_canais_json.py

      - name: Commit e push do canais.json atualizado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase || true
          git add canais.json
          git commit -m "Atualização automática do canais.json" || echo "Sem mudanças"
          git push