name: Merge canais_temp.json com canais.json

on:
  push:
    paths:
      - canais_temp.json
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: pip install -U pip

    - name: Rodar script de merge
      run: |
        python merge_canais_json.py
        mv canais_atualizado.json canais.json

    - name: Commit e push do canais.json atualizado
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add canais.json
        git commit -m "Merge automático do canais_temp.json no canais.json" || true
        git push
