name: Merge canais_temp.json com canais.json

on:
  workflow_dispatch:
  push:
    paths:
      - canais_temp.json

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar script de merge
        run: python merge_canais_json.py

      - name: Commit e push do canais.json atualizado
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main --rebase
          git add canais.json
          git commit -m "Merge automático do canais_temp.json no canais.json" || echo "Nada para commitar"
          git push origin main
