name: Merge canais_temp.json com canais.json

on:
  push:
    paths:
      - 'canais_temp.json'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install --upgrade pip

      - name: Rodar script de merge
        run: python merge_canais_json.py

      - name: Commit e push do canais.json atualizado
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add canais.json
          git commit -m "Merge automático do canais_temp.json no canais.json" || echo "Nenhuma mudança para commitar."
          git pull --rebase
          git push