name: Rotação de links IPTV

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas
  workflow_dispatch:

jobs:
  rotacionar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Rodar rotacionar_links.py
      run: python rotacionar_links.py

    - name: Commit e push do canais.json
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git pull --rebase
        git add canais.json
        git commit -m "Rotação automática de links IPTV"
        git push
