name: Rotacionar links IPTV por desempenho

on:
  schedule:
    - cron: "0 * * * *"  # roda a cada hora
  workflow_dispatch:

jobs:
  rotacionar:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: pip install requests

    - name: Rodar script de rotação de links
      run: |
        python rotacionar_links.py

    - name: Commit e push do canais.json atualizado
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add canais.json _falhas.json
        git commit -m "Rotação automática de links IPTV" || echo "Sem mudanças"
        git push
