name: Rotacionar links dos canais

on:
  workflow_dispatch:

jobs:
  rotacionar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar rotacionar_links.py
        run: python rotacionar_links.py

      - name: Commit e push do canais.json rotacionado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase || true
          git add canais.json
          git commit -m "Rotação automática dos links dos canais" || echo "Sem mudanças"
          git push